install:
  - set PATH=%PATH%;C:\msys64\mingw32\bin

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1

build_script:
  - cd miniupnpc
  - mingw32-make -f Makefile.mingw
  - mkdir miniupnpc_build
  - cd miniupnpc_build
  - ps: cmake -G "$($env:CMAKE_GENERATOR)$($env:CMAKE_GENERATOR_SUFFIX)" -DCMAKE_BUILD_TYPE="$($env:CONFIGURATION)" ..
  - ps: cmake --build . --config "$($env:CONFIGURATION)"  -- /m /v:normal
  - upnpc-static.exe -l
