install:
  - set PATH=%PATH%;C:\msys64\mingw32\bin

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

os: Visual Studio 2015

environment:
  matrix:
    - generator: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - generator: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - generator: "Visual Studio 14 2015"
    - generator: "Visual Studio 14 2015 Win64"

build_script:
  - ps: |
      cd miniupnpc
      mingw32-make -f Makefile.mingw
      mkdir miniupnpc_build
      cd miniupnpc_build
      cmake -G "$($env:generator)" -DCMAKE_BUILD_TYPE="$($env:CONFIGURATION)" -DIPHLPAPI_LIBRARY="" -DWINSOCK2_LIBRARY="" ..
      cmake --build . --config "$($env:CONFIGURATION)"  -- /m /v:normal

test_script:
  - miniupnpc\miniupnpc_build\upnpc-static.exe -l
